### ISSUE TITLE
Knowledge Base x OpenSearch Serverless 対応 (kuromoji あり Hybrid Search)

### ISSUE THREAD

**Issue by tbrand** [aws-samples/generative-ai-use-cases-jp#465]
## TODO
- [ ] Knowledge Base が CDK から作成できる => まだ無理ぽ
- [ ] OpenSearch Serverless の index に kuromoji が設定できる => 問い合わせ中
- [ ] Hybrid Search で frontend から retrieve できる => 上2つができれば可能
- [ ] プロンプトを整える => 同上
- [ ] 新たなユースケースの作成 => 同上

## 関連
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/442
